server:
  servlet:
    context-path: /api
spring:
  config:
    import:
      optional:classpath:/secret.yml
  server:
    port: '8080'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      maximum-pool-size: '4'
    username: postgres
    password: MrCroc1234
    url: jdbc:log4jdbc:postgresql://127.0.0.1:5432/ii
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            token-uri: https://nid.naver.com/oauth2.0/token
  application:
    name: ii

app:
  base-uri: http://localhost:8080
  web-uri: http://52.141.48.164:3000

logging:
  config: classpath:log4j2.xml
