server:
  server:
  port: 443 # HTTPS 포트 설정
  ssl:
    enabled: true
    key-store: classpath:ssl/hlemont.xyz.pfx # .pfx 인증서 경로
    key-store-password: tkdlqjek!2 # 인증서 비밀번호
    key-store-type: PKCS12 # 인증서 형식
  servlet:
    context-path: /api

spring:
  config:
    import:
      optional:classpath:/secret.yml
  server:
    port: '8080'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      maximum-pool-size: '4'
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            token-uri: https://nid.naver.com/oauth2.0/token
  application:
    name: ii

app:
  base-uri: https://api.hlemont.xyz
  web-uri: https://web.hlemont.xyz

logging:
  config: classpath:log4j2.xml
